spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  cloud:
    stream:
      bindings:
        item1OutPut:
          destination: item11
          group: item1